refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{X(job_id)}{h([{l:0.1}|{d(%y%m%d %H:%M:%S)}|{P}|{M}:{f}:{L}])} {m}{n}"
  requests:
    kind: file
    path: "log/requests.log"
    encoder:
      pattern: "([{l:0.1}|{d(%y%m%d %H:%M:%S)}|{M}:{f}:{L}]) {m}{n}"
root:
  level: debug
  appenders:
    - stdout
loggers:
  app::backend::db:
    level: info
  app::requests:
    level: info
    appenders:
      - requests
    additive: false
